service:
  http:
    port: 8080
  oauth:
    state:
      entropy: 8
    consent:
      url: http://127.0.0.1:8080/fake_consent
    clients:
      - id: 3acf718f-6dd4-4618-b58a-68ffc628f956
        name: service/heimdall
        secret: Xtr4vmMYd9lg2rPq
      - id: 554ea2d9-f65e-4c01-a76d-31ba6d1ad023
        name: sample/confidential
        secret: BBgTuLPxf09RBjHD
      - id: 24a293f3-5fcd-4176-acf7-e7beba4ed9fa
        name: sample/public